# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Medjat < Formula
  desc "Medjat CLI for memory-native AI agents"
  homepage "https://medjat.dev"
  version "0.1.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/darknet-developer/Medjat/releases/download/v0.1.3/medjat_0.1.3_darwin_amd64.tar.gz"
      sha256 "d3df945099045f491cd73f00906b7ba4b60a468b49ccbb054a14dde3921b4b10"

      define_method(:install) do
        bin.install "medjat"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/darknet-developer/Medjat/releases/download/v0.1.3/medjat_0.1.3_darwin_arm64.tar.gz"
      sha256 "580dda7a64a320a29a1beb36c30a2d0c4f74899557884ac104dfbfdde06a9932"

      define_method(:install) do
        bin.install "medjat"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/darknet-developer/Medjat/releases/download/v0.1.3/medjat_0.1.3_linux_amd64.tar.gz"
      sha256 "90d3479dcdf36ad4c203be66558f97ccfd611ede50f298bdb25d10d69afd1155"
      define_method(:install) do
        bin.install "medjat"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/darknet-developer/Medjat/releases/download/v0.1.3/medjat_0.1.3_linux_arm64.tar.gz"
      sha256 "95ac13212e0b27796f9779b7031fdf81dc96d34756a0a4cc8850ca24e69b40c5"
      define_method(:install) do
        bin.install "medjat"
      end
    end
  end

  test do
    system "#{bin}/medjat", "help"
  end
end
