# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Medjat < Formula
  desc "Medjat CLI for memory-native AI agents"
  homepage "https://medjat.dev"
  version "0.1.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/darknet-developer/Medjat/releases/download/v0.1.1/medjat_0.1.1_darwin_amd64.tar.gz"
      sha256 "2d0f927393bb8706d048b3c064f0c2eba65b2c43ad98b59ad4351a0c03f00442"

      define_method(:install) do
        bin.install "medjat"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/darknet-developer/Medjat/releases/download/v0.1.1/medjat_0.1.1_darwin_arm64.tar.gz"
      sha256 "43331df3a8663917631bc72679e933c47a22001c7b9b54d1675be1d2fc441ab6"

      define_method(:install) do
        bin.install "medjat"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/darknet-developer/Medjat/releases/download/v0.1.1/medjat_0.1.1_linux_amd64.tar.gz"
      sha256 "5c65fc09e79083c74c0d476c83b4505f74f801a5828751782ca959fd873f4faa"
      define_method(:install) do
        bin.install "medjat"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/darknet-developer/Medjat/releases/download/v0.1.1/medjat_0.1.1_linux_arm64.tar.gz"
      sha256 "85891df5421f3d26e30748e68692fbfa38ea499f6a14c9b51ad1e8c624c53d44"
      define_method(:install) do
        bin.install "medjat"
      end
    end
  end

  test do
    system "#{bin}/medjat", "help"
  end
end
